/* Autogenerated with kurento-module-creator */

#include "SamplePluginFilter-js-MVInternal.hpp"
#include <KurentoException.hpp>
#include <jsonrpc/JsonSerializer.hpp>
#include "MediaPipeline.hpp"

namespace kurento
{
namespace module
{
namespace sampleplugin-js-MV
{

void SamplePluginFilter-js-MVMethodSetFilterType::invoke (std::shared_ptr<SamplePluginFilter-js-MV> obj)
{
  if (!obj) {
    throw KurentoException (MEDIA_OBJECT_NOT_FOUND, "Invalid object while invoking method SamplePluginFilter-js-MV::setFilterType");
  }

  return obj->setFilterType (filterType);
}

void SamplePluginFilter-js-MVMethodSetFilterType::Serialize (kurento::JsonSerializer &s)
{
  if (s.IsWriter) {
    s.SerializeNVP (filterType);

  } else {
    if (s.JsonValue.isNull ()) {
      throw KurentoException (MARSHALL_ERROR,
                              "'operationParams' is required");
    } else if (!s.JsonValue.isObject ()){
      throw KurentoException (MARSHALL_ERROR,
                              "'operationParams' should be an object");
    }

    if (!s.JsonValue.isMember ("filterType") || !s.JsonValue["filterType"].isConvertibleTo (Json::ValueType::intValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'filterType' parameter should be a integer");
    }

    s.SerializeNVP (filterType);

  }
}

void SamplePluginFilter-js-MVMethodSetEdgeThreshold::invoke (std::shared_ptr<SamplePluginFilter-js-MV> obj)
{
  if (!obj) {
    throw KurentoException (MEDIA_OBJECT_NOT_FOUND, "Invalid object while invoking method SamplePluginFilter-js-MV::setEdgeThreshold");
  }

  return obj->setEdgeThreshold (edgeValue);
}

void SamplePluginFilter-js-MVMethodSetEdgeThreshold::Serialize (kurento::JsonSerializer &s)
{
  if (s.IsWriter) {
    s.SerializeNVP (edgeValue);

  } else {
    if (s.JsonValue.isNull ()) {
      throw KurentoException (MARSHALL_ERROR,
                              "'operationParams' is required");
    } else if (!s.JsonValue.isObject ()){
      throw KurentoException (MARSHALL_ERROR,
                              "'operationParams' should be an object");
    }

    if (!s.JsonValue.isMember ("edgeValue") || !s.JsonValue["edgeValue"].isConvertibleTo (Json::ValueType::intValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'edgeValue' parameter should be a integer");
    }

    s.SerializeNVP (edgeValue);

  }
}

std::shared_ptr<MediaPipeline> SamplePluginFilter-js-MVConstructor::getMediaPipeline ()
{
  return mediaPipeline;
}

void SamplePluginFilter-js-MVConstructor::Serialize (kurento::JsonSerializer &s)
{
  if (s.IsWriter) {
    s.SerializeNVP (mediaPipeline);

  } else {
    if (s.JsonValue.isNull ()) {
      throw KurentoException (MARSHALL_ERROR,
                              "'constructorParams' is required");
    } else if (!s.JsonValue.isObject ()){
      throw KurentoException (MARSHALL_ERROR,
                              "'constructorParams' should be an object");
    }

    if (!s.JsonValue.isMember ("mediaPipeline") || !s.JsonValue["mediaPipeline"].isConvertibleTo (Json::ValueType::stringValue) ) {
      throw KurentoException (MARSHALL_ERROR,
                              "'mediaPipeline' parameter should be a string");
    }

    s.SerializeNVP (mediaPipeline);

  }
}

} /* sampleplugin-js-MV */
} /* module */
} /* kurento */
