/* Autogenerated with kurento-module-creator */

#ifndef __SAMPLE_PLUGIN_FILTER-JS-MV_INTERNAL_HPP__
#define __SAMPLE_PLUGIN_FILTER-JS-MV_INTERNAL_HPP__

#include "SamplePluginFilter-js-MV.hpp"

namespace kurento
{
class JsonSerializer;
}

namespace kurento
{
class MediaPipeline;
} /* kurento */

namespace kurento
{
namespace module
{
namespace sampleplugin-js-MV
{

class SamplePluginFilter-js-MVMethodSetFilterType
{
public:
  SamplePluginFilter-js-MVMethodSetFilterType() {}
  ~SamplePluginFilter-js-MVMethodSetFilterType() {}

  void invoke (std::shared_ptr<SamplePluginFilter-js-MV> obj);
  void Serialize (JsonSerializer &serializer);

  int getFilterType () {
    return filterType;
  }

  void setFilterType (int filterType) {
    this->filterType = filterType;
  }

private:
  int filterType;
};

class SamplePluginFilter-js-MVMethodSetEdgeThreshold
{
public:
  SamplePluginFilter-js-MVMethodSetEdgeThreshold() {}
  ~SamplePluginFilter-js-MVMethodSetEdgeThreshold() {}

  void invoke (std::shared_ptr<SamplePluginFilter-js-MV> obj);
  void Serialize (JsonSerializer &serializer);

  int getEdgeValue () {
    return edgeValue;
  }

  void setEdgeValue (int edgeValue) {
    this->edgeValue = edgeValue;
  }

private:
  int edgeValue;
};

class SamplePluginFilter-js-MVConstructor
{
public:
  SamplePluginFilter-js-MVConstructor () {}
  ~SamplePluginFilter-js-MVConstructor () {}

  void Serialize (JsonSerializer &serializer);

  std::shared_ptr<MediaPipeline> getMediaPipeline ();

  void setMediaPipeline (std::shared_ptr<MediaPipeline> mediaPipeline) {
    this->mediaPipeline = mediaPipeline;
  }

private:
  std::shared_ptr<MediaPipeline> mediaPipeline;
};

} /* sampleplugin-js-MV */
} /* module */
} /* kurento */

#endif /*  __SAMPLE_PLUGIN_FILTER-JS-MV_INTERNAL_HPP__ */
