# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/markos/Downloads/3kms-plugin-sample-MV

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/markos/Downloads/3kms-plugin-sample-MV/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/markos/Downloads/3kms-plugin-sample-MV/build/CMakeFiles /home/markos/Downloads/3kms-plugin-sample-MV/build/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/markos/Downloads/3kms-plugin-sample-MV/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named generate_code

# Build rule for target.
generate_code: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 generate_code
.PHONY : generate_code

# fast build rule for target.
generate_code/fast:
	$(MAKE) -f src/server/CMakeFiles/generate_code.dir/build.make src/server/CMakeFiles/generate_code.dir/build
.PHONY : generate_code/fast

#=============================================================================
# Target rules for targets named kmssampleplugin-js-mvimpl

# Build rule for target.
kmssampleplugin-js-mvimpl: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kmssampleplugin-js-mvimpl
.PHONY : kmssampleplugin-js-mvimpl

# fast build rule for target.
kmssampleplugin-js-mvimpl/fast:
	$(MAKE) -f src/server/CMakeFiles/kmssampleplugin-js-mvimpl.dir/build.make src/server/CMakeFiles/kmssampleplugin-js-mvimpl.dir/build
.PHONY : kmssampleplugin-js-mvimpl/fast

#=============================================================================
# Target rules for targets named kmssampleplugin-js-mvinterface

# Build rule for target.
kmssampleplugin-js-mvinterface: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kmssampleplugin-js-mvinterface
.PHONY : kmssampleplugin-js-mvinterface

# fast build rule for target.
kmssampleplugin-js-mvinterface/fast:
	$(MAKE) -f src/server/CMakeFiles/kmssampleplugin-js-mvinterface.dir/build.make src/server/CMakeFiles/kmssampleplugin-js-mvinterface.dir/build
.PHONY : kmssampleplugin-js-mvinterface/fast

#=============================================================================
# Target rules for targets named kmssampleplugin-js-mvmodule

# Build rule for target.
kmssampleplugin-js-mvmodule: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kmssampleplugin-js-mvmodule
.PHONY : kmssampleplugin-js-mvmodule

# fast build rule for target.
kmssampleplugin-js-mvmodule/fast:
	$(MAKE) -f src/server/CMakeFiles/kmssampleplugin-js-mvmodule.dir/build.make src/server/CMakeFiles/kmssampleplugin-js-mvmodule.dir/build
.PHONY : kmssampleplugin-js-mvmodule/fast

#=============================================================================
# Target rules for targets named kmssampleplugin-js-mvplugins

# Build rule for target.
kmssampleplugin-js-mvplugins: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 kmssampleplugin-js-mvplugins
.PHONY : kmssampleplugin-js-mvplugins

# fast build rule for target.
kmssampleplugin-js-mvplugins/fast:
	$(MAKE) -f src/gst-plugins/CMakeFiles/kmssampleplugin-js-mvplugins.dir/build.make src/gst-plugins/CMakeFiles/kmssampleplugin-js-mvplugins.dir/build
.PHONY : kmssampleplugin-js-mvplugins/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... generate_code"
	@echo "... kmssampleplugin-js-mvimpl"
	@echo "... kmssampleplugin-js-mvinterface"
	@echo "... kmssampleplugin-js-mvmodule"
	@echo "... kmssampleplugin-js-mvplugins"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

