/* Autogenerated with kurento-module-creator */

#include "FactoryRegistrar.hpp"

#include <SamplePluginFilter_js_mvImplFactory.hpp>
#include <SamplePluginFilter_js_mv.hpp>

extern "C" {

  const kurento::FactoryRegistrar *getFactoryRegistrar ();

}

const kurento::FactoryRegistrar *
getFactoryRegistrar ()
{
  static bool loaded = false;
  static std::map<std::string, std::shared_ptr<kurento::Factory>> factories;

  if (!loaded) {
    factories["SamplePluginFilter_js_mv"] = std::shared_ptr <kurento::Factory> (new kurento::module::sampleplugin-js-mv::SamplePluginFilter_js_mvImplFactory() );
    loaded = true;
  }

  static kurento::FactoryRegistrar factory (factories);
  return &factory;
}
