/* Autogenerated with kurento-module-creator */

#include "FactoryRegistrar.hpp"

#include <SamplePluginFilter-js-MVImplFactory.hpp>
#include <SamplePluginFilter-js-MV.hpp>

extern "C" {

  const kurento::FactoryRegistrar *getFactoryRegistrar ();

}

const kurento::FactoryRegistrar *
getFactoryRegistrar ()
{
  static bool loaded = false;
  static std::map<std::string, std::shared_ptr<kurento::Factory>> factories;

  if (!loaded) {
    factories["SamplePluginFilter-js-MV"] = std::shared_ptr <kurento::Factory> (new kurento::module::sampleplugin-js-MV::SamplePluginFilter-js-MVImplFactory() );
    loaded = true;
  }

  static kurento::FactoryRegistrar factory (factories);
  return &factory;
}
