/* Autogenerated with kurento-module-creator */

#ifndef __SAMPLE_PLUGIN_FILTER-JS-MV_IMPL_FACTORY_HPP__
#define __SAMPLE_PLUGIN_FILTER-JS-MV_IMPL_FACTORY_HPP__

#include "SamplePluginFilter-js-MVImpl.hpp"
#include "FilterImplFactory.hpp"
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace sampleplugin-js-MV
{

class SamplePluginFilter-js-MVImplFactory : public virtual FilterImplFactory
{
public:
  SamplePluginFilter-js-MVImplFactory () {};

  virtual std::string getName () const {
    return "SamplePluginFilter-js-MV";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* sampleplugin-js-MV */
} /* module */
} /* kurento */

#endif /*  __SAMPLE_PLUGIN_FILTER-JS-MV_IMPL_FACTORY_HPP__ */