/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "SamplePluginFilter-js-MVImpl.hpp"
#include "SamplePluginFilter-js-MVImplFactory.hpp"
#include "SamplePluginFilter-js-MVInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{
namespace module
{
namespace sampleplugin-js-MV
{

MediaObjectImpl *SamplePluginFilter-js-MVImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  SamplePluginFilter-js-MVConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline() );
}

void
SamplePluginFilter-js-MVImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  if (methodName == "setFilterType") {
    kurento::JsonSerializer s (false);
    SamplePluginFilter-js-MVMethodSetFilterType method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<SamplePluginFilter-js-MV> (obj) );
    return;
  }

  if (methodName == "setEdgeThreshold") {
    kurento::JsonSerializer s (false);
    SamplePluginFilter-js-MVMethodSetEdgeThreshold method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<SamplePluginFilter-js-MV> (obj) );
    return;
  }

  FilterImpl::invoke (obj, methodName, params, response);
}

bool
SamplePluginFilter-js-MVImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return FilterImpl::connect (eventType, handler);
}

void
SamplePluginFilter-js-MVImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'SamplePluginFilter-js-MVImpl' cannot be deserialized as an object");
  }
}
} /* sampleplugin-js-MV */
} /* module */
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::module::sampleplugin-js-MV::SamplePluginFilter-js-MVImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::module::sampleplugin-js-MV::SamplePluginFilter-js-MVImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::module::sampleplugin-js-MV::SamplePluginFilter-js-MVImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::module::sampleplugin-js-MV::SamplePluginFilter-js-MV> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::module::sampleplugin-js-MV::SamplePluginFilter-js-MVImpl> aux = std::dynamic_pointer_cast<kurento::module::sampleplugin-js-MV::SamplePluginFilter-js-MVImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::module::sampleplugin-js-MV::SamplePluginFilter-js-MV> (aux);
}

} /* kurento */