/* Autogenerated with kurento-module-creator */

#include <gst/gst.h>
#include "MediaPipeline.hpp"
#include "SamplePluginFilter_js_mvImpl.hpp"
#include "SamplePluginFilter_js_mvImplFactory.hpp"
#include "SamplePluginFilter_js_mvInternal.hpp"
#include <jsonrpc/JsonSerializer.hpp>
#include <KurentoException.hpp>

using kurento::KurentoException;

namespace kurento
{
namespace module
{
namespace sampleplugin-js-mv
{

MediaObjectImpl *SamplePluginFilter_js_mvImplFactory::createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const
{
  kurento::JsonSerializer s (false);
  SamplePluginFilter_js_mvConstructor constructor;

  s.JsonValue = params;
  constructor.Serialize (s);

  return createObject (conf, constructor.getMediaPipeline() );
}

void
SamplePluginFilter_js_mvImpl::invoke (std::shared_ptr<MediaObjectImpl> obj, const std::string &methodName, const Json::Value &params, Json::Value &response)
{
  if (methodName == "setFilterType") {
    kurento::JsonSerializer s (false);
    SamplePluginFilter_js_mvMethodSetFilterType method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<SamplePluginFilter_js_mv> (obj) );
    return;
  }

  if (methodName == "setEdgeThreshold") {
    kurento::JsonSerializer s (false);
    SamplePluginFilter_js_mvMethodSetEdgeThreshold method;

    s.JsonValue = params;
    method.Serialize (s);

    method.invoke (std::dynamic_pointer_cast<SamplePluginFilter_js_mv> (obj) );
    return;
  }

  FilterImpl::invoke (obj, methodName, params, response);
}

bool
SamplePluginFilter_js_mvImpl::connect (const std::string &eventType, std::shared_ptr<EventHandler> handler)
{

  return FilterImpl::connect (eventType, handler);
}

void
SamplePluginFilter_js_mvImpl::Serialize (JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    try {
      Json::Value v (getId() );

      serializer.JsonValue = v;
    } catch (std::bad_cast &e) {
    }
  } else {
    throw KurentoException (MARSHALL_ERROR,
                            "'SamplePluginFilter_js_mvImpl' cannot be deserialized as an object");
  }
}
} /* sampleplugin-js-mv */
} /* module */
} /* kurento */

namespace kurento
{

void
Serialize (std::shared_ptr<kurento::module::sampleplugin-js-mv::SamplePluginFilter_js_mvImpl> &object, JsonSerializer &serializer)
{
  if (serializer.IsWriter) {
    if (object) {
      object->Serialize (serializer);
    }
  } else {
    std::shared_ptr<kurento::MediaObjectImpl> aux;
    aux = kurento::module::sampleplugin-js-mv::SamplePluginFilter_js_mvImplFactory::getObject (JsonFixes::getString(serializer.JsonValue) );
    object = std::dynamic_pointer_cast<kurento::module::sampleplugin-js-mv::SamplePluginFilter_js_mvImpl> (aux);
  }
}

void
Serialize (std::shared_ptr<kurento::module::sampleplugin-js-mv::SamplePluginFilter_js_mv> &object, JsonSerializer &serializer)
{
  std::shared_ptr<kurento::module::sampleplugin-js-mv::SamplePluginFilter_js_mvImpl> aux = std::dynamic_pointer_cast<kurento::module::sampleplugin-js-mv::SamplePluginFilter_js_mvImpl> (object);

  Serialize (aux, serializer);
  object = std::dynamic_pointer_cast <kurento::module::sampleplugin-js-mv::SamplePluginFilter_js_mv> (aux);
}

} /* kurento */