/* Autogenerated with kurento-module-creator */

#ifndef __SAMPLE_PLUGIN_FILTER_JS_MV_IMPL_FACTORY_HPP__
#define __SAMPLE_PLUGIN_FILTER_JS_MV_IMPL_FACTORY_HPP__

#include "SamplePluginFilter_js_mvImpl.hpp"
#include "FilterImplFactory.hpp"
#include <MediaObjectImpl.hpp>
#include <boost/property_tree/ptree.hpp>

namespace kurento
{
namespace module
{
namespace sampleplugin_js_mv
{

class SamplePluginFilter_js_mvImplFactory : public virtual FilterImplFactory
{
public:
  SamplePluginFilter_js_mvImplFactory () {};

  virtual std::string getName () const {
    return "SamplePluginFilter_js_mv";
  };

private:

  virtual MediaObjectImpl *createObjectPointer (const boost::property_tree::ptree &conf, const Json::Value &params) const;

  MediaObjectImpl *createObject (const boost::property_tree::ptree &conf, std::shared_ptr<MediaPipeline> mediaPipeline) const;
};

} /* sampleplugin_js_mv */
} /* module */
} /* kurento */

#endif /*  __SAMPLE_PLUGIN_FILTER_JS_MV_IMPL_FACTORY_HPP__ */