/* Autogenerated with kurento-module-creator */

#include "SamplePluginFilter_js_mvImpl.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace sampleplugin-js-mv
{

void dummySampleplugin-js-mv ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<SamplePluginFilter_js_mv> object;

    s.SerializeNVP (object);
  }
}

} /* sampleplugin-js-mv */
} /* module */
} /* kurento */
