/* Autogenerated with kurento-module-creator */

#include "SamplePluginFilter-js-MVImpl.hpp"

#include <jsonrpc/JsonSerializer.hpp>

namespace kurento
{
namespace module
{
namespace sampleplugin-js-MV
{

void dummySampleplugin-js-MV ()
{
  {
    JsonSerializer s (true);
    std::shared_ptr<SamplePluginFilter-js-MV> object;

    s.SerializeNVP (object);
  }
}

} /* sampleplugin-js-MV */
} /* module */
} /* kurento */
